# Generated by Django 4.1.3 on 2022-11-09 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UploadApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="files", name="File_name",),
    ]
